Week8
SergeDot/node-express-course pull request #10
Opened 2024-04-01 17:13 UTC by SergeDot

2024-04-08 23:43 UTC, ethanarns requested changes
Well done overall, but a password is also very important to this. Everything else seems to be good though, should be a quick turnaround.

2024-04-08 23:43 UTC, ethanarns commented on 05-JWT-Basics/preferred/public/files/tp.svg
This theme as a whole was a really clever idea. I love it!

2024-04-08 23:43 UTC, ethanarns commented on 05-JWT-Basics/preferred/controllers/main.js
> +  const { name } = req.body;
You'll need both name and password for this assignment. You got `name` pulling correctly though!

2024-04-08 23:43 UTC, ethanarns commented on 05-JWT-Basics/preferred/controllers/main.js
> +  const token = jwt.sign({ name }, process.env.JWT_SECRET, { expiresIn: process.env.TOKEN_EXPIRATION });
This is smart, good security practice

2024-04-12 19:25 UTC, SergeDot commented on 05-JWT-Basics/preferred/controllers/main.js
> +  const { name } = req.body;
Done, added the password functionality

2024-04-12 19:30 UTC, merged